import Header from "@/components/Header";
import { handleSubmit } from "@/utils";
import Head from "next/head";
import Image from "next/image";
import { NextRouter, useRouter } from "next/router";
import { FormEvent } from "react";

export default function Home() {
  const router= useRouter()

  return (
    <>
      <Head>
        <title>Social Crypt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="w-[100vw] px-10 lg:px-20">
        <section
          id="input"
          className="py-10 flex flex-col gap-10 lg:flex-row lg:justify-around lg:items-center"
        >
          <div className="lg:w-2/5">
            <Image
              alt="Hero Illustration"
              src="/hero.png"
              width="550"
              height="450"
              className="w-full max-w-[55rem] mx-auto rounded-3xl"
            />
          </div>
          <div className="lg:w-2/5">
            <h1 className="text-3xl lg:text-5xl font-bold">Crypt Check an Article!</h1>
            <form className="mt-5 text-xl space-y-6" onSubmit={e => handleSubmit(e.currentTarget["URL"].value, router)}>
              <span>
                <label htmlFor="URl" >Enter Article URL</label>
                <input
                  type="text"
                  name="URL"
                  className="w-full outline-none border-2 border-blue-600 p-2 pl-4 rounded-xl mt-2 placeholder:text-sm
                focus:ring-4 ring-blue-400 ring-opacity-40 "
                  placeholder="https://example.com/some-article"
                />
              </span>

              <button
                className="w-full bg-blue-400 py-2 rounded-xl  
            hover:ring-4 ring-blue-400 ring-opacity-40
            active:scale-90 transition-all"
              >
                Analyze
              </button>
            </form>
          </div>
        </section>

        <article>
          <div>
            <h1>About us</h1>
            <p>
              Nowadays, it can be difficult to tell the difference between
              credible information and misinformation online 🌐. To solve this
              problem, Social Crypt provides users with a solution that lets
              them discover the truth behind the articles they read 📰. This
              application analyzes articles and detects misleading/propaganda
              information, coordinated bot activity, sentiment of entities
              mentioned, Social Media Activity of the same information, Source
              Authenticity and a lot more.
            </p>
            <p>
              Social Crypt is the solution you need to remain informed and make
              informed decisions, whether you're a journalist, researcher, or
              simply concerned about the reliability of the information you
              consume ⚠️.
            </p>
          </div>
          <div>

          </div>
        </article>
      </main>
    </>
  );
}
