name: Lint Changed Python Files

on: [push, pull_request]

jobs:
  pylint:
    name: Run Pylint on changed files
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your Python version

    - name: Install Pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Get changed Python files
      id: files
      run: |
        files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.py$')
        if [ -z "$files" ]; then
          echo "No Python files changed"
          exit 0
        fi
        echo "::set-output name=files::$files"

    - name: Run Pylint on changed files
      id: pylint
      run: |
        pylint_output=$(pylint ${{ steps.files.outputs.files }} 2>&1) || true
        echo "::set-output name=output::$pylint_output"

    - name: Post results as a comment
      if: steps.pylint.outputs.output
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const output = `Pylint Results:\n\`\`\`\n${{ steps.pylint.outputs.output }}\n\`\`\`\nPlease review the linting errors and make the necessary changes.`;
          const issue_number = context.issue.number || context.payload.pull_request.number;
          github.issues.createComment({
            issue_number: issue_number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          });
