name: Lint Changed Python Files

on: [push, pull_request]

jobs:
  pylint:
    name: Run Pylint on changed files
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetches all history for all branches and tags

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your Python version

    - name: Install Pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Get changed Python files
      id: files
      run: |
        base_sha=$(jq -r ".pull_request.base.sha // .before" $GITHUB_EVENT_PATH)
        head_sha=$(jq -r ".pull_request.head.sha // .after" $GITHUB_EVENT_PATH)
        if [ -z "$base_sha" ] || [ -z "$head_sha" ]; then
          echo "Base or head commit SHA missing"
          exit 0
        fi
        files=$(git diff --name-only $base_sha $head_sha | grep '\.py$')
        if [ -z "$files" ]; then
          echo "No Python files changed"
          exit 0
        fi
        echo "::set-output name=files::$files"

    - name: Run Pylint on changed files
      id: pylint
      run: |
        pylint_output=$(pylint ${{ steps.files.outputs.files }} 2>&1) || true
        echo "::set-output name=output::$pylint_output"

    - name: Post results as a comment
      if: steps.pylint.outputs.output
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const output = `Pylint Results:\n\`\`\`\n${{ steps.pylint.outputs.output }}\n\`\`\`\nPlease review the linting errors and make the necessary changes.`;
          const issue_n
